baseURL = "https://photo.simon-hu.org/"
copyright = "© Suowei Hu"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Australia/Canberra"
timeout = "3600s"
title = "Simon's Photo"
theme = "gallery"

[params]
  defaultTheme = "light"
  title = "Simon's Photo"
  description = "Simon's Photo"
  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"
  [params.author]
    email = "suowei.h@gmail.com"
    name = "Suowei (Simon) Hu"
  [params.socialIcons]
    linkedin = "https://www.linkedin.com/in/suowei-hu-0249b0181/"
    github = "https://github.com/SuoweiHu"
    email = "mailto:suowei.h@gmail.com"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.footer]]

[services]
  [services.rss]
    limit = 100